### ISSUE TITLE
After the configuration, I still can't receive mail with action mailbox

### ISSUE THREAD

**Issue by Sylor-huang** [Loumaris/action-mailbox-docker-postfix-relay#1]
Hi, @ChristianHeimke 

I want to build a mailbox server with `Rails action mailbox` in docker 

**I just need to be able to receive emails ， but no need to send email.**

I have made some modifications with reference to your code ，but not use your docker repo.

But now after  when I send email from gmail (or other) to my custom email (like: xxx@domain.cn) , it shows deliveried successfully but I can not receive emails in my rails app.

**I don't know which of my configurations were wrong， could you help me. Thanks so much~**

####  My configurations

1. my dns `mail.xxx.cn` is ping successful, it can get bytes from IP address.

![image](https://user-images.githubusercontent.com/26167245/116553107-58e52700-a92c-11eb-8a0b-a064678b5848.png)

2. My online-server had open port： 443，25, 587

![image](https://user-images.githubusercontent.com/26167245/116553772-11ab6600-a92d-11eb-9bfe-0f5ef35c0b8f.png)

3. I used docker to deploy my rails server

 ![image](https://user-images.githubusercontent.com/26167245/116554174-78308400-a92d-11eb-8412-ed11ad59db6d.png)

4. My `ApplicationMailbox` and `comments_mailbox` like this: 

```ruby

class ApplicationMailbox < ActionMailbox::Base
  
  #routing /@xxx.com/i => :comments
  routing :all => :comments
end
```

```ruby
class CommentsMailbox < ApplicationMailbox
  def process
    p mail.decoded
  rescue => e 
    p e
  end
end

```

4. My nginx configuration is like this: 

```ruby

user xxx;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
  worker_connections 1024;
}

http {
  ...

location ~ /(api|rails)/ {
                proxy_pass http://127.0.0.1:3005;
                proxy_set_header X-Real-IP       $remote_addr;
                proxy_set_header X-Forwarded-For 
                $proxy_add_x_forwarded_for;
                proxy_set_header  HTTP_X_FORWARDED_FOR $remote_addr;
                proxy_set_header NginX-Proxy   true;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                autoindex_exact_size on;
                autoindex_localtime on;
                proxy_read_timeout 240s;
          }
...
}
```

5. Postfix configuration

```ruby
# /usr/local/bin/email_forwarder.sh

#!/bin/sh
export HOME=/home/airdrop
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/airdrop/.rvm/bin
export RVM_ROOT=/home/airdrop/.rvm/scripts/rvm
cd /home/airdrop/login_member && bundle exec rails action_mailbox:ingress:postfix URL='http://localhost:3005/rails/action_mailbox/relay/inbound_emails' INGRESS_PASSWORD='xxxxxx'

```

```ruby
# /etc/postfix/virtual_aliases
#airdrop is created user

@xxx.cn  airdrop@xxx.cn

# /etc/postfix/transport

xxx.cn    forward_to_rails:
```

```ruby
# /etc/postfix/master.cf

...
forward_to_rails   unix  -       n       n       -       -       pipe
  flags=Xhq user=airdrop:airdrop argv=/usr/local/bin/email_forwarder.sh
  ${nexthop} ${user}
```

Then I restart the postfix `sudo service postfix restart`, it runs ok.

When I send Email from other email to ydddd@xxx.cn (my custom emails), I can not receive any mail.log

![image](https://user-images.githubusercontent.com/26167245/116554676-0dcc1380-a92e-11eb-9237-356e729405fe.png)

What's wrong with it？Is this a problem for NGINX?? Could you please help me? Thanks so much~~

**Comment by ChristianHeimke** [comment]
HI @Sylor-huang,


debugging action mailbox can be really hard... so I try my best ;-) 

Your config looks good so far 👍  did you also run the postmap commands from the dockerfile: https://github.com/Loumaris/action-mailbox-docker-postfix-relay/blob/master/Dockerfile#L43
Those will tell postfix how to handle the alias etc.

nginx shouldn't be the problem, because your config refers still to localhost for actionmailbox: 
```
... 
URL='http://localhost:3005/rails/action_mailbox/relay/inbound_emails' INGRESS_PASSWORD='xxxxxx'
```
(is the relay script executable?)

Could you please provide your postfix logs (access/error logs, maybe some syslogs) after sending your mail from external? This could help us to find the error.

**Comment by Sylor-huang** [comment]
@ChristianHeimke , I'm so happly that  you can reply to me.  Thanks so much~~~~

**I had get `Command output: /usr/local/bin/email_forwarder.sh: 5: bundle: not found` errors this time.**


 - [x] I had run the postmap commands and  generate the `.db` file

```ruby
postmap /etc/postfix/transport && \
postmap /etc/postfix/virtual_aliases && \
postconf maillog_file=/dev/stdout
```

- [x] I can get the postfix logs in this way 

 > It seems that after : `postconf maillog_file=/dev/stdout`  and then  should run `sudo postfix start-fg`. In this way, I can start the postfix and get the log

> related article:  http://postfix.cs.utah.edu/source/experimental/postfix-3.4-20190202.RELEASE_NOTES
...
  To write logs to Postfix logfile (see below for logfile rotation): 
    # postfix stop
    # postconf maillog_file=/var/log/postfix.log
    # postfix start
 To write logs to stdout, typically while Postfix runs in a container:
    # postconf maillog_file=/dev/stdout
    # postfix start-fg
...

- [x] In the log, I can see the mails, but get the errors with `Command not found`

![image](https://user-images.githubusercontent.com/26167245/116653184-3a793d00-a9b9-11eb-81c9-48420ed926ee.png)
![image](https://user-images.githubusercontent.com/26167245/116653211-4bc24980-a9b9-11eb-9d20-c5875678e623.png)

```ruby
# /usr/local/bin/email_forwarder.sh

#!/bin/sh
export HOME=/home/airdrop
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/airdrop/.rvm/bin
export RVM_ROOT=/home/airdrop/.rvm/scripts/rvm
cd /home/airdrop/login_member && bundle exec rails action_mailbox:ingress:postfix URL='http://localhost:3005/rails/action_mailbox/relay/inbound_emails' INGRESS_PASSWORD='xxxxxx'

```

I had just run  `cd /home/airdrop/login_member && bundle exec rails action_mailbox:ingress:postfix URL='http://localhost:3005/rails/action_mailbox/relay/inbound_emails' INGRESS_PASSWORD='xxxxxx'` in terminal, it seems ok:

![image](https://user-images.githubusercontent.com/26167245/116651235-57ac0c80-a9b5-11eb-8499-cca1dbe6a8f9.png)

- [x] Get `$PATH` has errors

![image](https://user-images.githubusercontent.com/26167245/116651583-1b2ce080-a9b6-11eb-9deb-03c78f25ea52.png)


What's wrong maybe with this error?  Is it going to be $PATH related in  email_forwarder.sh ? 

Thanks again~~~ @ChristianHeimke

**Comment by ChristianHeimke** [comment]
Alright, thanks for providing the information.

As far as I remember, postfix is running as an own user (you can check it with `ps aux | grep postfix` and see the user, it should be `postfix` or maybe `root`) and can't access the rvm / bundler / gems inside another homedirectory. 

`rvm` is install for your `airdrop` user - but not for postfix. you can try to install it system-wide (multiuser), for postfix or use the system ruby and bundler. this should fix the problem (hopefully).

**Comment by Sylor-huang** [comment]
@ChristianHeimke , thanks so much, you are right, my postfix is running as root, I will try to install rvm for root again. 

![image](https://user-images.githubusercontent.com/26167245/116667832-36581a00-a9cf-11eb-9826-556ce44ca606.png)

**Comment by Sylor-huang** [comment]
@ChristianHeimke , I'm sorry to bother you again.

- I had installed `rvm` and `ruby` by root, but I also get the `permission denied` errors

![image](https://user-images.githubusercontent.com/26167245/116767485-fb072b00-aa62-11eb-9135-239c8b436af0.png)

![image](https://user-images.githubusercontent.com/26167245/116767318-0c036c80-aa62-11eb-9594-9b3a90412730.png)

- After I used the sudo, I also get the erros

```ruby
#!/bin/sh
export HOME=/home/airdrop
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.rvm/bin
export RVM_ROOT=/root/.rvm/scripts
cd /home/airdrop/login_member && sudo bundle exec rails action_mailbox:ingress:postfix URL='http://localhost:3005/rails/action_mailbox/relay/inbound_emails' INGRESS_PASSWORD='xxxx'
```

![image](https://user-images.githubusercontent.com/26167245/116767388-6a304f80-aa62-11eb-9683-d73a50d42c5e.png)

Could you help me to see what the problem is?  Thanks so much ~~

**Comment by ChristianHeimke** [comment]
I guess this has two reasons: 
* missing execute permissions for the script
* postfix is not a sudo'er

## missing execute permissions:
have a look here: https://github.com/Loumaris/action-mailbox-docker-postfix-relay/blob/master/Dockerfile#L52 
You need to set the  `+x` flag at least

## postfix is not a sudo'er

Either you install rvm as postfix user (run `su postfix` as root and run the user-based installation) or add `postfix` as password'less sudoer: 

```
echo "postfix  ALL=(ALL)  NOPASSWD: ALL" > /etc/sudoers.d/postfix
```

please keep in mind - this is quick and dirty. for production systems, postfix should only be able to run the relay script as sudo user. but for now, for getting it working this is okay.

**Comment by Sylor-huang** [comment]
@ChristianHeimke  Thanks so much. At last, I solve the `bundle` errors in the following way：

 - [x] Changed the `email_forwarder.sh` file (same as your `replay.sh`) from `#!/bin/sh` to `#!/bin/bash -l` 

- [x]  Run the command: 


```ruby
echo "postfix  ALL=(ALL)  NOPASSWD: ALL" > /etc/sudoers.d/postfix
```

 it works fine. 

Thanks so much for your help, you are a great man 👍

**Comment by ChristianHeimke** [comment]
@Sylor-huang I'm happy that I could help you :) 

happy hacking!
